---
version: "3.8"
services:
  movies:
    image: nayannaidu8/paytmmovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: nayannaidu8/paytmtrain:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: nayannaidu8/paytmrecharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: nayannaidu8/paytmdth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3
